### ISSUE TITLE
방에서 나갈때 생기는 버그

### ISSUE THREAD

**Issue by dunde-o** [boostcampwm-2021/WEB17-LiarKing#184]
- [x] 방에서 일반 유저가 나갈때 방이 사라지는 버그

**Comment by dunde-o** [comment]
방장이 아니라 한명이 남았을 때 방이 사라지는 것으로 추정!

**Comment by kskim625** [comment]
세 명이 있다가 두 명이 나가면 방이 사라지는 이슈가 아직 남아있음 ㅠㅠ
